### ISSUE TITLE
Tauri 2.0 Support?

### ISSUE THREAD

**Issue by jaydevelopsstuff** [crabnebula-dev/drag-rs#30]
As far as I can tell these are the two roadblocks to getting this working with Tauri 2.0:
- There are dependency conflicts with GTK related crates
- `HasRawWindowHandle` is deprecated due to `tauri-2.0.0-beta.3` upgrading to `raw-window-handle` 0.6.0.

Any plans to get this crate working with 2.0 Beta or are we waiting for a Release Candidate?

**Comment by lucasfernog-crabnebula** [comment]
We were waiting on Tauri v2 to more stable to implement this. Basically we need a new crate that uses Tauri v2 instead of v1, and move the v1 crate out of the workspace.

**Comment by piotrostr** [comment]
We did get it to work in https://github.com/audiogenai/drag for OSX, Image param is not supported and some features might be limited but the drag and drop indeed works with v2-beta :)

**Comment by ayangweb** [comment]
Hey👋, tauri v2 released a stable version, hope to support it soon!🌹

**Comment by lucasfernog-crabnebula** [comment]
I'll take a look at this over the week :)

**Comment by ayangweb** [comment]
Maybe I could try pr a v2 version?

**Comment by lucasfernog** [comment]
Hey if you want to give it a try let me know how it goes :) i can at least help if you start a PR

**Comment by ayangweb** [comment]
Ok, I'll adapt tauri v2 first, then you can do some optimization.

**Comment by lucasfernog** [comment]
should be pretty straightforward, i'm only worried about the gtk and windows dependencies updates

**Comment by ayangweb** [comment]
tauri v2 多了一个插件权限的问题🫣依赖版本问题只能在使用的时候看看，我也不懂
