### ISSUE TITLE
Execute other commands after dragging

### ISSUE THREAD

**Issue by Vzz1c** [crabnebula-dev/drag-rs#9]
I hope to add a custom command to be executed after dragging. It can be any system command instead of just copying the file to the path. This will greatly improve the degree of freedom. For example, if I want to create a shortcut to the dragged file, I may need to first Create this shortcut method locally. After dragging, I still need to manually delete the temporarily created shortcut. The premise of these operations is that I need to obtain the target path first, but there seems to be no relevant API provided at present.
At some point, a file drag operation may require movement.

**Comment by denjell-crabnebula** [comment]
Yes, callbacks are intended to be added in a next step. Thanks for your feedback!

**Comment by lucasfernog-crabnebula** [comment]
I believe #16 provides the callback you need.

**Comment by Vzz1c** [comment]
@denjell-crabnebula @lucasfernog-crabnebula 
I can think of two options:
1. At the moment when the mouse is released after dragging, get the path of the current drag destination, so that I can do something before dragging. For example, I want to change the dragged `.png` into a `.jpg` after dragging. Then I can manually copy or move the `.jpg` to this path by calling the command. At this time, I need to disable the default copying behavior after dragging. This method will not generate temporary files. What I need is a path to the dragged destination. As for what files need to be placed in this path in the end, you can freely implement it, which is similar to simulating the effect of native dragging.
2. The dragged `item` is not provided directly, but in the form of a function. I can determine the file path that needs to be dragged in the function. I can first convert `.png` to `.jpg` in this function, and then it will be dragged. The file is `.jpg`, which generates a temporary file `.jpg`
Of course, no one may have such a need to convert `.png` to `.jpg`, but it maximizes flexibility.

**Comment by Vzz1c** [comment]
https://github.com/superlistapp/super_native_extensions/tree/main/super_drag_and_drop
I see useful functionality in this repository, to implement drag and drop of file types, you need to change the code in the example to fileUrl
